title: BurritoBandit861 Portfilio
         This is my portfolio showcasing my projects and skills.
baseurl: "" 
url: "https://BurritoBandit861.github.io" 
theme: minima # replace with your chosen theme from the list
